import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { setTimeout as delay } from 'node:timers/promises';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { ulid } from 'ulid';
import { featuresRepository, migrateToLatest } from '@adl/db';
import {
  AdlYmlSchema,
  DaemonConfigSchema,
  type AdlYml,
  type DaemonConfig,
} from '@adl/core/config';
import { startDaemon } from '../../src/index.js';
import { withTempRepo } from '../../../workspace/test/helpers/temp-repo.js';
import {
  MIGRATIONS_DIR,
  withTempDb,
} from '../../../db/test/helpers/temp-db.js';

/**
 * A commit made during a GATE stage by anything other than ADL is NOT vouched
 * for — it is judged with the developer's next commit (M08 step 8.6, the
 * adversarial review's finding on `DEBT.md` D-8-A-1).
 *
 * D-8-A-1 was: ROLE-11 diffed the developer's new commit against the previous
 * round's `head_sha` — the developer's OWN previous commit, recorded before any
 * gate ran — so whatever a gate committed afterwards was judged as the
 * developer's work. Step 8.6's first commit fixed it by vouching for every
 * gate stage's HEAD range. The step's adversarial review then found what that
 * vouched for: a gate stage runs developer-controlled code in the developer's
 * worktree — `commands.test` is typically `npm test`, whose script the
 * developer writes — so a developer could have that code commit an edit to a
 * protected path, and the edit would be vouched for and never diffed again.
 *
 * So ADL now vouches only for the commit it makes itself (the carry-back of a
 * tester's tests, `tester-tests-committed.test.ts` proves it is not blamed).
 * A commit made by anything else during a gate stage stays outside the vouched
 * tip, and ROLE-11 judges it with the developer's next commit. This scenario is
 * that rule, through a real daemon: a plain-command gate commits
 * `tests/generated.txt` under `protected_paths: ['tests/**']` and fails; round
 * 2's developer touches only `agent-output.txt`; and the round escalates, naming
 * the gate's file. A formatter or codegen gate that commits into a protected
 * path is therefore a configuration a human must look at, and the reason says
 * so without claiming the developer typed it.
 *
 * **Watched failing:** with every gate stage's range vouched for (this step's
 * first commit, `f8949f5`), round 2 went green and the change was never seen.
 *
 * Every layer is production except the billed `claude` binary.
 */

const API_TOKEN = `test-token-${ulid()}`;

const TRACER_WORKER_ENTRY = fileURLToPath(
  new URL('../helpers/tracer-worker-entry.ts', import.meta.url),
);
const FAKE_CLAUDE_SUCCESS = fileURLToPath(
  new URL('../helpers/fake-claude-success.mjs', import.meta.url),
);

async function waitUntil(
  predicate: () => boolean | Promise<boolean>,
  { timeoutMs = 60_000, intervalMs = 25 } = {},
): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  for (;;) {
    if (await predicate()) return;
    if (Date.now() >= deadline) {
      throw new Error(
        `waitUntil: condition was not satisfied within ${String(timeoutMs)}ms`,
      );
    }
    await delay(intervalMs);
  }
}

/**
 * A gate that commits a generated file on its first run and fails, then
 * passes. Run with the worktree as its cwd, so its `git commit` lands on the
 * feature's branch exactly as a real committing gate's would. The counter
 * lives outside every workspace, for `command-gate-loop.test.ts`'s reason.
 *
 * An `-e` program rather than a helper module: it is the external program
 * under test, and spawning `git` from it is what a committing gate does.
 */
function commitThenFail(counterPath: string): readonly string[] {
  return [
    process.execPath,
    '-e',
    [
      "const fs = require('node:fs');",
      "const { execFileSync } = require('node:child_process');",
      `const counter = ${JSON.stringify(counterPath)};`,
      "const runs = Number(fs.readFileSync(counter, 'utf8')) + 1;",
      'fs.writeFileSync(counter, String(runs));',
      'if (runs === 1) {',
      "  fs.mkdirSync('tests', { recursive: true });",
      "  fs.writeFileSync('tests/generated.txt', 'generated by the gate\\n');",
      "  execFileSync('git', ['add', 'tests/generated.txt'], { stdio: 'ignore' });",
      "  execFileSync('git', ['commit', '-q', '-m', 'gate: regenerate'], { stdio: 'ignore' });",
      "  process.stderr.write('FAIL: regenerated, please re-run\\n');",
      '  process.exit(1);',
      '}',
      'process.exit(0);',
    ].join('\n'),
  ];
}

describe('scenario: a commit a gate stage made is judged, never vouched for', () => {
  it(
    'a protected path a plain-command gate committed in round 1 escalates at round 2’s developer commit',
    { timeout: 180_000 },
    async () => {
      await withTempDb(async ({ db, filePath }) => {
        await migrateToLatest(db, MIGRATIONS_DIR);

        await withTempRepo(async ({ mainRepo, scratchRoot, git }) => {
          const folder = `gate-commit-${ulid()}`;
          const featureDir = `features/${folder}`;
          await mkdir(join(mainRepo, featureDir), { recursive: true });
          await writeFile(
            join(mainRepo, featureDir, 'spec.md'),
            '# Title\n\nRegenerate\n\n## Acceptance Criteria\n\n- The gate runs.\n',
            'utf8',
          );
          await git.add(`${featureDir}/spec.md`);
          await git.raw(['commit', '-m', 'add feature']);
          const defaultBranch = (
            await git.raw(['branch', '--show-current'])
          ).trim();

          const counterPath = join(scratchRoot, '..', 'gate-commit-runs');
          await writeFile(counterPath, '0', 'utf8');

          const adlYml: AdlYml = AdlYmlSchema.parse({
            version: 1,
            protected_paths: ['tests/**'],
            commands: {
              build: { argv: ['true'] },
              start: { argv: ['true'] },
              test: { argv: ['true'] },
              teardown: { argv: ['true'] },
            },
            pipeline: [
              'develop',
              {
                harness: 'regenerate',
                with: {
                  command: {
                    argv: commitThenFail(counterPath),
                    timeout: '60s',
                  },
                },
              },
            ],
          });

          const daemonConfig: DaemonConfig = DaemonConfigSchema.parse({
            limits: { max_rounds: 2 },
            repos: [
              {
                id: 'repo-1',
                remote_url: 'https://example.invalid/repo.git',
                default_branch: defaultBranch,
                forge: 'github',
                features_dir: 'features',
              },
            ],
          });

          const handle = await startDaemon({
            dbFilePath: filePath,
            port: 0,
            apiToken: API_TOKEN,
            migrationsDir: MIGRATIONS_DIR,
            leaseTtlMs: 60_000,
            heartbeatIntervalMs: 500,
            daemonConfig,
            resolveAdlYml: () => adlYml,
            mainRepo,
            scratchRoot,
            workerEntryPath: TRACER_WORKER_ENTRY,
            workerExecArgv: ['--import', 'tsx'],
            workerEnv: {
              ADL_TRACER_CLAUDE_BINARY_JSON: JSON.stringify([
                process.execPath,
                FAKE_CLAUDE_SUCCESS,
              ]),
            },
            dispatchIntervalMs: 20,
          });

          try {
            const response = await fetch(
              `http://127.0.0.1:${handle.port}/dev-run/${folder}`,
              {
                method: 'POST',
                headers: { Authorization: `Bearer ${API_TOKEN}` },
              },
            );
            expect(response.status).toBe(200);
            const { featureId } = (await response.json()) as {
              featureId: string;
            };

            await waitUntil(async () => {
              const row = await featuresRepository(db).findById(featureId);
              return row?.state === 'publishing' || row?.state === 'escalated';
            });

            const rounds = await db
              .selectFrom('rounds')
              .selectAll()
              .where('feature_id', '=', featureId)
              .orderBy('number')
              .execute();

            // Round 2's developer commit is judged together with everything
            // since the last tip ADL vouched for — which is round 1's
            // developer commit, not the gate's.
            expect(rounds.map((round) => round.outcome)).toEqual([
              'send_back',
              'escalate',
            ]);
            expect(rounds[0]?.vouched_sha).toBe(rounds[0]?.head_sha);
            const reason = (
              JSON.parse(rounds[1]?.outcome_json ?? '{}') as { reason?: string }
            ).reason;
            expect(reason).toContain('tests/generated.txt');
            // Without claiming the developer typed it.
            expect(reason).toContain(
              'changed between the last commit ADL vouched for',
            );

            // The gate really did commit, and ran once — round 2 ended at the
            // developer's commit, before any gate.
            expect(Number(await readFile(counterPath, 'utf8'))).toBe(1);
            const gateCommits = (
              await git.raw([
                'log',
                '--format=%s',
                `${rounds[0]!.head_sha!}..${rounds[1]!.head_sha!}`,
              ])
            )
              .trim()
              .split('\n');
            expect(gateCommits).toContain('gate: regenerate');
          } finally {
            await handle.stop();
          }
        });
      });
    },
  );
});
