import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { setTimeout as delay } from 'node:timers/promises';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { ulid } from 'ulid';
import { featuresRepository, migrateToLatest } from '@adl/db';
import {
  AdlYmlSchema,
  DaemonConfigSchema,
  type AdlYml,
  type DaemonConfig,
} from '@adl/core/config';
import { startDaemon } from '../../src/index.js';
import { withTempRepo } from '../../../workspace/test/helpers/temp-repo.js';
import {
  MIGRATIONS_DIR,
  withTempDb,
} from '../../../db/test/helpers/temp-db.js';

/**
 * A commit a GATE made is never attributed to the developer (M08 step 8.6,
 * closing `DEBT.md` D-8-A-1).
 *
 * The defect: ROLE-11's protected-path check diffed "the previous round's
 * `head_sha`" against the developer's new commit, and `head_sha` is the
 * developer's sha, recorded before any gate runs. So a commit a gate made in
 * round N fell outside round N's recorded head and inside round N+1's diff,
 * and was judged there as the developer's work — a hard escalation naming a
 * path the developer never touched and could do nothing about.
 *
 * It was reachable on `main` before M08 through 7.3's plain-command gate,
 * which is an arbitrary program running in the developer's worktree, and that
 * is exactly the shape this scenario uses: a gate that commits a generated
 * file under `tests/` — a formatter or a codegen step committing its own
 * output — with `protected_paths: ['tests/**']`, the schema's own worked
 * example. Its first run commits and fails, so there IS a round 2; its second
 * run passes. Round 2's developer touches only `agent-output.txt`.
 *
 * **Watched failing:** against `main` before this step's fix, the feature
 * escalated at round 2 with a reason naming `tests/generated.txt`.
 *
 * Every layer is production except the billed `claude` binary.
 */

const API_TOKEN = `test-token-${ulid()}`;

const TRACER_WORKER_ENTRY = fileURLToPath(
  new URL('../helpers/tracer-worker-entry.ts', import.meta.url),
);
const FAKE_CLAUDE_SUCCESS = fileURLToPath(
  new URL('../helpers/fake-claude-success.mjs', import.meta.url),
);

async function waitUntil(
  predicate: () => boolean | Promise<boolean>,
  { timeoutMs = 60_000, intervalMs = 25 } = {},
): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  for (;;) {
    if (await predicate()) return;
    if (Date.now() >= deadline) {
      throw new Error(
        `waitUntil: condition was not satisfied within ${String(timeoutMs)}ms`,
      );
    }
    await delay(intervalMs);
  }
}

/**
 * A gate that commits a generated file on its first run and fails, then
 * passes. Run with the worktree as its cwd, so its `git commit` lands on the
 * feature's branch exactly as a real committing gate's would. The counter
 * lives outside every workspace, for `command-gate-loop.test.ts`'s reason.
 *
 * An `-e` program rather than a helper module: it is the external program
 * under test, and spawning `git` from it is what a committing gate does.
 */
function commitThenFail(counterPath: string): readonly string[] {
  return [
    process.execPath,
    '-e',
    [
      "const fs = require('node:fs');",
      "const { execFileSync } = require('node:child_process');",
      `const counter = ${JSON.stringify(counterPath)};`,
      "const runs = Number(fs.readFileSync(counter, 'utf8')) + 1;",
      'fs.writeFileSync(counter, String(runs));',
      'if (runs === 1) {',
      "  fs.mkdirSync('tests', { recursive: true });",
      "  fs.writeFileSync('tests/generated.txt', 'generated by the gate\\n');",
      "  execFileSync('git', ['add', 'tests/generated.txt'], { stdio: 'ignore' });",
      "  execFileSync('git', ['commit', '-q', '-m', 'gate: regenerate'], { stdio: 'ignore' });",
      "  process.stderr.write('FAIL: regenerated, please re-run\\n');",
      '  process.exit(1);',
      '}',
      'process.exit(0);',
    ].join('\n'),
  ];
}

describe('scenario: a gate’s own commit is not blamed on the developer (D-8-A-1)', () => {
  it(
    'a committing gate in round 1 does not trip ROLE-11 on round 2’s developer commit',
    { timeout: 180_000 },
    async () => {
      await withTempDb(async ({ db, filePath }) => {
        await migrateToLatest(db, MIGRATIONS_DIR);

        await withTempRepo(async ({ mainRepo, scratchRoot, git }) => {
          const folder = `gate-commit-${ulid()}`;
          const featureDir = `features/${folder}`;
          await mkdir(join(mainRepo, featureDir), { recursive: true });
          await writeFile(
            join(mainRepo, featureDir, 'spec.md'),
            '# Title\n\nRegenerate\n\n## Acceptance Criteria\n\n- The gate runs.\n',
            'utf8',
          );
          await git.add(`${featureDir}/spec.md`);
          await git.raw(['commit', '-m', 'add feature']);
          const defaultBranch = (
            await git.raw(['branch', '--show-current'])
          ).trim();

          const counterPath = join(scratchRoot, '..', 'gate-commit-runs');
          await writeFile(counterPath, '0', 'utf8');

          const adlYml: AdlYml = AdlYmlSchema.parse({
            version: 1,
            protected_paths: ['tests/**'],
            commands: {
              build: { argv: ['true'] },
              start: { argv: ['true'] },
              test: { argv: ['true'] },
              teardown: { argv: ['true'] },
            },
            pipeline: [
              'develop',
              {
                harness: 'regenerate',
                with: {
                  command: {
                    argv: commitThenFail(counterPath),
                    timeout: '60s',
                  },
                },
              },
            ],
          });

          const daemonConfig: DaemonConfig = DaemonConfigSchema.parse({
            limits: { max_rounds: 2 },
            repos: [
              {
                id: 'repo-1',
                remote_url: 'https://example.invalid/repo.git',
                default_branch: defaultBranch,
                forge: 'github',
                features_dir: 'features',
              },
            ],
          });

          const handle = await startDaemon({
            dbFilePath: filePath,
            port: 0,
            apiToken: API_TOKEN,
            migrationsDir: MIGRATIONS_DIR,
            leaseTtlMs: 60_000,
            heartbeatIntervalMs: 500,
            daemonConfig,
            resolveAdlYml: () => adlYml,
            mainRepo,
            scratchRoot,
            workerEntryPath: TRACER_WORKER_ENTRY,
            workerExecArgv: ['--import', 'tsx'],
            workerEnv: {
              ADL_TRACER_CLAUDE_BINARY_JSON: JSON.stringify([
                process.execPath,
                FAKE_CLAUDE_SUCCESS,
              ]),
            },
            dispatchIntervalMs: 20,
          });

          try {
            const response = await fetch(
              `http://127.0.0.1:${handle.port}/dev-run/${folder}`,
              {
                method: 'POST',
                headers: { Authorization: `Bearer ${API_TOKEN}` },
              },
            );
            expect(response.status).toBe(200);
            const { featureId } = (await response.json()) as {
              featureId: string;
            };

            await waitUntil(async () => {
              const row = await featuresRepository(db).findById(featureId);
              return row?.state === 'publishing' || row?.state === 'escalated';
            });

            const rounds = await db
              .selectFrom('rounds')
              .selectAll()
              .where('feature_id', '=', featureId)
              .orderBy('number')
              .execute();

            // The fix: round 2's developer commit is judged on what IT
            // changed, so the round goes green rather than escalating with
            // `tests/generated.txt` named as the developer's violation.
            const reasons = rounds.map((round) => round.outcome_json ?? '');
            expect(reasons.join('\n')).not.toContain('tests/generated.txt');
            expect(rounds.map((round) => round.outcome)).toEqual([
              'send_back',
              'green',
            ]);

            // The gate really did commit, and really did run twice — without
            // these the green round below could be a gate that never wrote
            // anything.
            expect(Number(await readFile(counterPath, 'utf8'))).toBe(2);
            const gateCommits = (
              await git.raw([
                'log',
                '--format=%s',
                `${rounds[0]!.head_sha!}..${rounds[1]!.head_sha!}`,
              ])
            )
              .trim()
              .split('\n');
            expect(gateCommits).toContain('gate: regenerate');
          } finally {
            await handle.stop();
          }
        });
      });
    },
  );
});
